#!/usr/bin/env ruby
require "optparse"
require "rcsv"

options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: rcsv [options]"

  opts.on("-iFILE", "--input FILE", "Input CSV file") { |v| options[:input] = v }
  opts.on("-oFILE", "--output FILE", "Output TXT file") { |v| options[:output] = v }
  opts.on("-fCOLUMN VALUE", "--filter-for COLUMN VALUE", Array, "Filter rows") do |v|
    options[:filter_col], options[:filter_val] = v
  end
  opts.on("-h", "--help", "Show this message") do
    puts opts
    exit
  end
end.parse!

if options[:input].nil? || options[:output].nil?
  warn "Missing input or output file.\n\nUse -h for help."
  exit 1
end

RCSV.run(options[:input], options[:output], options[:filter_col], options[:filter_val])
